import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import ReBarChart from '../components/recharts-components/ReBarChart'
import DefaultLayout from '../layouts/Default'
import styles from '../../styles/Home.module.css'
import ReChartJs2 from './chartjs2'
import Recharts from './recharts'
import Nivo from './nivo'
import ReactVis from './reactvis'
import Victory from './victory'
// import "bulma/css/bulma.min.css";

const Home: NextPage = () => {
  return (
    <div className={styles.appWrapper}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      {/* <DefaultLayout title=''> */}

      <div className="columns">
        <div className="column">
          <Recharts />
        </div>
        <div className="column">
          <ReChartJs2 />
        </div>
        <div className="column">
          <Victory />
        </div>
        <div className="column">
          {/* <ReactVis /> */}
        </div>
      </div>


      {/* </DefaultLayout> */}

    </div>
  )
}

export default Home
