import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import styles from '../../styles/Home.module.css'
import ReSimpleBarChart from '../components/recharts-components/ReSimpleBarChart'
import { List } from '../DataStruct/List'

const Recharts: NextPage = () => {

    const [data, setData] = useState<any[]>([]);
    const [yAxisLabelText, setYAxisLabelText] = useState<string>('');

    useEffect(() => {
        makeData();
        setYAxisLabelText('Number of assignments')

        const list = new List();
        list.push('one');
        list.push('two');
        list.push('three');
        
        debugger

    }, [])

    const makeData = () => {
        const data: any[] = [];
        const colors = ['#ec84ee', '#0a70fd', '#1cce67', '#ff6263', '#01dcea', '#ffcc12', '#ff8e50', '#7b61ff', '#7b61ff', '#7b61ab'];
        colors.forEach((color, i) => {
            data.push({
                name: `Supplier ${i + 1}`,
                value: Math.floor(Math.random() * 10) + 1,
                color,
                drillDown1: makeDrillDown1(color, i + 1)
            })
        });
        setData(data);
        // console.log(data)
    }

    const makeDrillDown1 = (color: string, i: number): any[] => {
        const data: any[] = [];
        const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sept', 'Oct', 'Nov', 'Dev'];
        months.forEach(month => {
            data.push(
                {
                    name: month,
                    value: Math.floor(Math.random() * 10) + 1,
                    color,
                }
            )
        })
        return data
    }

    const onBarClick = (e: any) => {
        console.log(e)
    }

    return (
        <div className={styles.appWrapper}>
            <Head>
                <title>Recharts | Examples</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <ReSimpleBarChart
                data={data}
                width={500}
                height={300}
                yAxisLabelText={yAxisLabelText}
                onBarClick={onBarClick}
            />
        </div>
    )
}

export default Recharts
